-- liquibase formatted sql
-- changeset sasha:1
CREATE TABLE IF NOT EXISTS "user"
(
    user_id           BIGINT NOT NULL,
    registration_date date,
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

--changeset sasha:2
CREATE TABLE IF NOT EXISTS hiragana
(
    hieroglyph_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hieroglyph          VARCHAR(255),
    hieroglyph_pronouns VARCHAR(255),
    CONSTRAINT pk_hiragana PRIMARY KEY (hieroglyph_id)
);

CREATE TABLE IF NOT EXISTS katakana
(
    hieroglyph_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hieroglyph          VARCHAR(255),
    hieroglyph_pronouns VARCHAR(255),
    CONSTRAINT pk_katakana PRIMARY KEY (hieroglyph_id)
);

--changeset sasha:3
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS mode VARCHAR(255) DEFAULT 'TEXT_MODE' NULL;

--changeset sasha:4
CREATE TABLE IF NOT EXISTS task
(
    task_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_number INTEGER NOT NULL,
    question_count  INTEGER NOT NULL,
    user_id         BIGINT,
    CONSTRAINT pk_task PRIMARY KEY (task_id)
);

CREATE TABLE IF NOT EXISTS task_letters
(
    task_id      BIGINT       NOT NULL,
    letter_value VARCHAR(255),
    letter_key   VARCHAR(255) NOT NULL,
    CONSTRAINT pk_task_letters PRIMARY KEY (task_id, letter_key)
);

CREATE TABLE IF NOT EXISTS user_answers
(
    task_id           BIGINT NOT NULL,
    is_answer_correct BOOLEAN
);

ALTER TABLE task
    ADD CONSTRAINT fk_task_on_user FOREIGN KEY (user_id) REFERENCES "user" (user_id);

ALTER TABLE task_letters
    ADD CONSTRAINT fk_task_letters_on_task FOREIGN KEY (task_id) REFERENCES task (task_id);

ALTER TABLE user_answers
    ADD CONSTRAINT fk_user_answers_on_task FOREIGN KEY (task_id) REFERENCES task (task_id);